const types = {
  LOGIN_INFO: 'LOGIN_INFO',
  IS_FETCHING: 'IS_FETCHING',
  REQUEST_SUCCESS: 'REQUEST_SUCCESS',
  REQUEST_TOKEN_SUCCESS: 'REQUEST_TOKEN_SUCCESS',
  SCORE_UPDATE: 'SCORE_UPDATE',
  RESET_SCORE: 'RESET_SCORE',
  SAVE_TIMER: 'SAVE_TIMER',
  SAVE_PICTURE: 'SAVE_PICTURE',
};

export default types;
