const NEW_PLAYER = 'NEW_PLAYER';
const REQUEST_SUCESS = 'REQUEST_SUCESS';
const REQUEST_FAIL = 'REQUEST_FAILED';
const UPDATE_SCORE = 'UPDATE_SCORE';

export { NEW_PLAYER, REQUEST_SUCESS, REQUEST_FAIL, UPDATE_SCORE };
