const UPDATE_EMAIL = 'UPDATE_EMAIL';
const UPDATE_NAME = 'UPDATE_NAME';
const REQUEST_SUCESS = 'REQUEST_SUCESS';
const REQUEST_FAIL = 'REQUEST_FAILED';

export { UPDATE_EMAIL, UPDATE_NAME, REQUEST_SUCESS, REQUEST_FAIL };
