const UPDATE_EMAIL = 'UPDATE_EMAIL';
const UPDATE_NAME = 'UPDATE_NAME';
const REQUEST_SUCESS = 'REQUEST_SUCESS';
const REQUEST_FAIL = 'REQUEST_FAILED';
const UPDATE_TIME = 'UPDATE_TIME';

export { UPDATE_EMAIL, UPDATE_NAME, REQUEST_SUCESS, REQUEST_FAIL, UPDATE_TIME };
